SELECT *
FROM HR.EMPLEADOS
WHERE (DEPARTMENT_ID,HIRE_DATE) IN
(SELECT
    DEPARTMENT_ID DEPARTAMENTO,
    MIN(HIRE_DATE) FECHA_ANTIGUA
    FROM HR.EMPLEADOS
    GROUP BY DEPARTMENT_ID);


    
SELECT P.*, ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)) TIEMPO
FROM HR.EMPLEADOS P
WHERE (DEPARTMENT_ID,ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE))) IN
(SELECT
    DEPARTMENT_ID DEPARTAMENTO,
    MAX(ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)))
    FROM HR.EMPLEADOS
    GROUP BY DEPARTMENT_ID);
    
    
    