--01. CANTIDAD DE CAJAS POR PROVEEDOR
SELECT P.NAME_PROVE, COUNT(D.CAJA)
FROM MIBANCO.DETALLE D, MIBANCO.PROVEEDOR P
WHERE D.ID_PROVE = P.ID_PROVE
GROUP BY P.NAME_PROVE

--02. CANTIDAD DE CAJAS POR TIPO DE DOCUMENTO
SELECT T.NAME_TDOC, COUNT(D.CAJA) "NRO CAJAS"
FROM MIBANCO.DETALLE D, MIBANCO.TIPO_DOC T
WHERE D.ID_TDOC = T.ID_TDOC
GROUP BY T.NAME_TDOC

--03. CANTIDAD DE CAJAS POR AÑO
SELECT TO_CHAR(FECHA_D,'YYYY') ANIO, COUNT(CAJA)
FROM MIBANCO.DETALLE
GROUP BY TO_CHAR(FECHA_D,'YYYY')

--04. CANTIDAD DE CAJAS POR SISTEMA
SELECT S.NAME_SISTEMA, COUNT(D.CAJA)
FROM MIBANCO.DETALLE D, MIBANCO.SISTEMA S
WHERE D.ID_SISTEMA = S.ID_SISTEMA
GROUP BY S.NAME_SISTEMA

--05. CANTIDAD DE TIPOS DE DOCUMENTOS CONTRACTUALES
SELECT T.NAME_TDOC, COUNT(D.CAJA)
FROM MIBANCO.DETALLE D, MIBANCO.TIPO_DOC T
WHERE D.ID_TDOC = T.ID_TDOC
AND D.ID_TDOC IN ('PAGAR','CUADE','EXPED')
GROUP BY T.NAME_TDOC

--06. CANTIDAD DE DOCUMENTOS POR TIPO EN EL AÑO 2018
SELECT T.NAME_TDOC, COUNT(D.CAJA)
FROM MIBANCO.DETALLE D, MIBANCO.TIPO_DOC T
WHERE D.ID_TDOC = T.ID_TDOC
AND TO_CHAR(FECHA_D,'YYYY') = 2018
GROUP BY T.NAME_TDOC

--07. CANTIDAD DE CAJAS ENTRE 2010 Y 2018
SELECT TO_CHAR(FECHA_D,'YYYY') ANIO, COUNT(CAJA)
FROM MIBANCO.DETALLE
WHERE FECHA_D BETWEEN '01/01/2010' AND '31/12/2018'
GROUP BY TO_CHAR(FECHA_D,'YYYY')

--08. CANTIDAD DE CAJAS POR ESTADO
SELECT E.NAME_ESTADO, COUNT(D.CAJA)
FROM MIBANCO.DETALLE D, MIBANCO.ESTADO E
WHERE D.ID_ESTADO = E.ID_ESTADO
GROUP BY E.NAME_ESTADO

--09. CANTIDAD DE CAJAS POR AREA
SELECT A.NAME_AREA, COUNT(D.CAJA)
FROM MIBANCO.DETALLE D, MIBANCO.AREA A
WHERE D.ID_AREA = A.ID_AREA
GROUP BY A.NAME_AREA

--10. CANTIDAD DE CAJAS QUE EXCEDEN LOS FILES PERMITIDOS
SELECT P.NAME_PROVE, COUNT(D.CAJA) CAJAS_EXCEDEN
FROM MIBANCO.DETALLE D, MIBANCO.PROVEEDOR P
WHERE D.ID_PROVE = P.ID_PROVE
AND D.FILES > P.CAPACIDAD
GROUP BY P.NAME_PROVE

--11. CANTIDAD DE CAJAS POR DEPURAR EN TLI, IM Y POLY
SELECT P.NAME_PROVE, COUNT(D.CAJA) CAJAS_A_DEPURAR
FROM MIBANCO.DETALLE D, MIBANCO.PROVEEDOR P, MIBANCO.ESTADO E
WHERE D.ID_PROVE = P.ID_PROVE
AND D.ID_ESTADO = E.ID_ESTADO
GROUP BY P.NAME_PROVE

--12. CANTIDAD DE CAJAS DEL PROVEEDOR IM POR SISTEMAS
SELECT S.NAME_SISTEMA, COUNT(D.CAJA)
FROM MIBANCO.DETALLE D, MIBANCO.SISTEMA S
WHERE D.ID_SISTEMA = S.ID_SISTEMA
AND ID_PROVE = 'IM'
GROUP BY S.NAME_SISTEMA

--13. CANTIDAD DE CAJAS DEL 2008 DEL PROVEEDOR IM Y CON ESPACIO
SELECT COUNT(D.CAJA), TO_CHAR(D.FECHA_D,'YYYY') ANIO
FROM MIBANCO.DETALLE D, MIBANCO.PROVEEDOR P
WHERE D.FILES < P.CAPACIDAD
AND D.ID_PROVE = 'IM' AND TO_CHAR(D.FECHA_D,'YYYY') = 2008
GROUP BY TO_CHAR(D.FECHA_D,'YYYY')

--14. CANTIDAD DE CAJAS AL 100% POR AREA
SELECT A.NAME_AREA, COUNT(D.CAJA)
FROM MIBANCO.DETALLE D, MIBANCO.AREA A, MIBANCO.PROVEEDOR P
WHERE D.ID_AREA = A.ID_AREA
AND D.FILES = P.CAPACIDAD
GROUP BY A.NAME_AREA

--15. TIPOS DE DOCUMENTO QUE CONTIENEN LAS CAJAS AL 100%
SELECT T.NAME_TDOC, COUNT(D.CAJA) "NRO CAJAS"
FROM MIBANCO.DETALLE D, MIBANCO.TIPO_DOC T, MIBANCO.PROVEEDOR P
WHERE D.ID_TDOC = T.ID_TDOC
AND D.FILES = P.CAPACIDAD
GROUP BY T.NAME_TDOC

--16. CAJAS QUE SOBREPASARON SU CAPACIDAD MAXIMA POR PROVEEDOR
SELECT P.NAME_PROVE, COUNT(D.CAJA)
FROM MIBANCO.DETALLE D, MIBANCO.PROVEEDOR P
WHERE D.ID_PROVE = P.ID_PROVE
AND D.FILES = P.CAPACIDAD
GROUP BY P.NAME_PROVE

--17. CALCULAR COSTO DE INDEXACION POR FILE
SELECT P.NAME_PROVE, COUNT(D.CAJA) CAJAS_EXCEDEN
FROM MIBANCO.DETALLE D, MIBANCO.PROVEEDOR P
WHERE D.ID_PROVE = P.ID_PROVE
AND D.FILES > P.CAPACIDAD
GROUP BY P.NAME_PROVE

--18. CANTIDAD DE EXPEDIENTES EN POLY POR AÑOS
SELECT P.NAME_PROVE, COUNT(D.CAJA)
FROM MIBANCO.DETALLE D, MIBANCO.PROVEEDOR P
WHERE D.ID_PROVE = P.ID_PROVE
AND D.ID_TDOC = 'EXPED' AND D.ID_PROVE = 'POL'
GROUP BY P.NAME_PROVE

--19. CANTIDAD DE CAJAS QUE CONTIENEN PAGARE EN ESTADO TRASLADO Y QUE EXCEDAN LA CAPACIDAD DE FILES - CONVIENE MANTENER
SELECT E.NAME_ESTADO, COUNT(D.CAJA) CONVIENE_MANTENER
FROM MIBANCO.DETALLE D, MIBANCO.ESTADO E, MIBANCO.PROVEEDOR P
WHERE D.ID_ESTADO = E.ID_ESTADO
AND D.FILES > P.CAPACIDAD
AND D.ID_ESTADO = 'DEPUR'
AND D.ID_TDOC = 'PAGAR'
GROUP BY E.NAME_ESTADO

--20.

--CREANDO VISTA GENERAL
CREATE OR REPLACE VIEW MIBANCO.V_GRAL
AS
SELECT
D.CAJA CAJA,
D.N_PRESTAMO NRO_PRESTAMO,
D.NOM_APE APELLIDOS_NOMBRES,
D.COD_CLIENTE CODIGO_CLIENTE,
D.FECHA_D FECHA_DESEMBOLSO,
A.NAME_AREA AREA,
E.NAME_ESTADO ESTADO,
P.NAME_PROVE PROVEEDOR,
S.NAME_SISTEMA SISTEMA,
T.NAME_TDOC TIPO_DOCUMENTO,
D.FILES CAPACIDAD_ACTUAL
FROM MIBANCO.DETALLE D
INNER JOIN MIBANCO.AREA A ON D.ID_AREA = A.ID_AREA
INNER JOIN MIBANCO.ESTADO E ON D.ID_ESTADO = E.ID_ESTADO
INNER JOIN MIBANCO.PROVEEDOR P ON D.ID_PROVE = P.ID_PROVE
INNER JOIN MIBANCO.SISTEMA S ON D.ID_SISTEMA = S.ID_SISTEMA
INNER JOIN MIBANCO.TIPO_DOC T ON D.ID_TDOC = T.ID_TDOC

--VERIFICANDO REGISTROS DE LA VISTA CREADA
SELECT * FROM MIBANCO.V_GRAL

--VERIFICANDO DATOS POR NRO DE PRESTAMO EN LA VISTA
SELECT * FROM MIBANCO.V_GRAL
WHERE NRO_PRESTAMO IN ('20508863366','20535821098')
ORDER BY NRO_PRESTAMO


